INSERT INTO "GROUP" (NAME) VALUES ('Dies ist ein Satz, oder nicht?');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe2');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe3');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe4');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe5');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe6');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe7');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe8');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe9');
INSERT INTO "GROUP" (NAME) VALUES ('Gruppe10');

INSERT INTO EXPRESSION (CONTENT) VALUES ('Wort1');
INSERT INTO EXPRESSION (CONTENT) VALUES ('Wort2');
INSERT INTO EXPRESSION (CONTENT) VALUES ('Wort3');
INSERT INTO EXPRESSION (CONTENT) VALUES ('Wort4');
INSERT INTO EXPRESSION (CONTENT) VALUES ('Wort5');

INSERT INTO BELONGS_TO (NAME, CONTENT) VALUES ('Dies ist ein Satz, oder nicht?', 'Wort1');
INSERT INTO BELONGS_TO (NAME, CONTENT) VALUES ('Gruppe2', 'Wort1');
INSERT INTO BELONGS_TO (NAME, CONTENT) VALUES ('Gruppe2', 'Wort2');
INSERT INTO BELONGS_TO (NAME, CONTENT) VALUES ('Gruppe2', 'Wort3');
INSERT INTO BELONGS_TO (NAME, CONTENT) VALUES ('Gruppe3', 'Wort4');

